"""add_market_intelligence

Revision ID: 7437a19061f9
"""
from alembic import op
import sqlalchemy as sa

revision = '7437a19061f9'
down_revision = '57697e374cc0'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_collection_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('query', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('records_found', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('normalized_name', sa.String(length=256), nullable=False),
    sa.Column('manufacturer', sa.String(length=256), nullable=True),
    sa.Column('model', sa.String(length=256), nullable=True),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_products_normalized_name'), 'market_products', ['normalized_name'], unique=True)
    op.create_index(op.f('ix_market_products_sku'), 'market_products', ['sku'], unique=False)
    op.create_table('market_suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('normalized_name', sa.String(length=256), nullable=False),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('supplier_type', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_suppliers_normalized_name'), 'market_suppliers', ['normalized_name'], unique=True)
    op.create_table('market_price_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('pack_quantity', sa.Integer(), nullable=False),
    sa.Column('normalized_unit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('normalized_unit', sa.String(length=32), nullable=False),
    sa.Column('availability', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('tax_included', sa.Boolean(), nullable=False),
    sa.Column('shipping_included', sa.Boolean(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['market_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['market_suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_price_observations_collected_at'), 'market_price_observations', ['collected_at'], unique=False)
    op.create_index(op.f('ix_market_price_observations_product_id'), 'market_price_observations', ['product_id'], unique=False)
    op.create_index(op.f('ix_market_price_observations_supplier_id'), 'market_price_observations', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_price_observations_supplier_id'), table_name='market_price_observations')
    op.drop_index(op.f('ix_market_price_observations_product_id'), table_name='market_price_observations')
    op.drop_index(op.f('ix_market_price_observations_collected_at'), table_name='market_price_observations')
    op.drop_table('market_price_observations')
    op.drop_index(op.f('ix_market_suppliers_normalized_name'), table_name='market_suppliers')
    op.drop_table('market_suppliers')
    op.drop_index(op.f('ix_market_products_sku'), table_name='market_products')
    op.drop_index(op.f('ix_market_products_normalized_name'), table_name='market_products')
    op.drop_table('market_products')
    op.drop_table('market_collection_jobs')
    # ### end Alembic commands ###
