"""add_raw_fields_to_market_price_observations

Revision ID: a5ef76fb82ab
"""
from alembic import op
import sqlalchemy as sa

revision = 'a5ef76fb82ab'
down_revision = '7437a19061f9'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_price_observations', sa.Column('raw_product_name', sa.String(length=256), nullable=True))
    op.add_column('market_price_observations', sa.Column('raw_supplier_name', sa.String(length=256), nullable=True))
    op.add_column('market_price_observations', sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('market_price_observations', sa.Column('freshness', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_price_observations', 'freshness')
    op.drop_column('market_price_observations', 'quality_score')
    op.drop_column('market_price_observations', 'raw_supplier_name')
    op.drop_column('market_price_observations', 'raw_product_name')
    # ### end Alembic commands ###
